# Generated by Django 4.1.7 on 2023-04-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('pickup', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('message', models.TextField()),
            ],
        ),
    ]
